Load basic module stored locally at the same directory.

In [1]:
import o2a
a = o2a.o2a()

In [2]:
urns = ["vessel:heincke:dwd:air_temperature", "vessel:heincke:dwd:air_pressure"]
a.items(urns[1])

{'offset': 0,
 'hits': 1,
 'totalHits': 1,
 'records': [{'itemId': 583,
   'itemUuid': 'da07f00f-b51f-4bb4-8622-c95405c5846d',
   'itemUrl': 'https://registry.o2a-data.de/items/583',
   'code': 'vessel:heincke:dwd:air_pressure',
   'id': 9,
   'unit': 'hPa'}],
 'duration': 15}

Download data from data streams.

In [3]:

dateIn = "2024-03-18T20:00:00"
dateOut = "2024-03-19T09:24:28"
urns = ["vessel:heincke:dwd:air_temperature","vessel:heincke:dwd:air_pressure"]
a.downloadDataFromStreams(items = urns, begin = dateIn, end = dateOut, aggregateFunctions="STDDEV")

True

,datetime,vessel:heincke:dwd:air_temperature (stddev) [°C],vessel:heincke:dwd:air_pressure (stddev) [hPa]
0,2024-03-18 20:00:00,0.081650,0.000000
1,2024-03-18 21:00:00,0.104881,0.547723
2,2024-03-18 22:00:00,0.081650,0.000000
3,2024-03-18 23:00:00,0.040825,0.516398
4,2024-03-19 00:00:00,0.075277,0.000000
5,2024-03-19 01:00:00,0.000000,0.000000
6,2024-03-19 02:00:00,0.136626,0.516398
7,2024-03-19 03:00:00,0.081650,0.000000
8,2024-03-19 04:00:00,0.051640,0.000000
9,2024-03-19 05:00:00,0.051640,0.516398
10,2024-03-19 06:00:00,0.081650,0.000000
11,2024-03-19 07:00:00,0.063246,0.000000
12,2024-03-19 08:00:00,0.040825,0.000000
13,2024-03-19 09:00:00,0.152753,0.000000

In [4]:
a.downloadDataFromStreams(items = urns, begin = dateIn, end = dateOut, aggregate = 'MINUTE')

False

,datetime,vessel:heincke:dwd:air_temperature (mean) [°C],vessel:heincke:dwd:air_pressure (mean) [hPa]
0,2024-03-18 20:02:00,7.3,1018
1,2024-03-18 20:12:00,7.3,1018
2,2024-03-18 20:22:00,7.3,1018
3,2024-03-18 20:32:00,7.4,1018
4,2024-03-18 20:42:00,7.5,1018
...,...,...,...
76,2024-03-19 08:42:00,7.3,1017
77,2024-03-19 08:52:00,7.2,1017
78,2024-03-19 09:02:00,7.4,1017
79,2024-03-19 09:12:00,7.5,1017
80,2024-03-19 09:22:00,7.7,1017

Getting more metadata about an item. Either to be put in urn-syntax:

In [5]:
urn = "vessel:mya_ii:fb_741202:optode_9999a"

a.item(code = urn)

{'@uuid': '972f7341-7524-40ac-ad5d-1ab2b0603fe1',
 'id': 560,
 'created': '2016-06-27T00:00:00',
 'lastModified': '2024-01-17T19:17:13.759',
 'code': 'vessel:mya_ii:fb_741202:optode_9999a',
 'shortName': 'Optode_9999a',
 'longName': 'Optode',
 'description': 'The Aanderaa oxygen optodes are based on the ability of selected substances to act as dynamic uorescence quenchers. The uorescent indicator is a special platinum porphyrin complex embedded in a gas permeable foil that is exposed to the surrounding water. A black optical isolation coating protects the complex from sunlight and uorescent particles in the water. This sensing foil is attached to a window providing optical access for the measuring system from inside awatertight housing.Thefoilisexcitedbymodulated blue light, and the phase of a returned red light is measured. By linearizing and temperature compensating, with an incorporated temperature sensor, the absolute O2 concentration can be determined.',
 'model': 'OXYGEN OPTODE 4835',
 'manufacturer': 'Aanderaa',
 'serialNumber': '9999a',
 'inventoryNumber': '',
 'citation': '10013/sensor.51ea3572-e557-4b2b-a202-3b749a87bf84',
 'parentId': 508,
 'status': {'@uuid': 'a080ff68-30b2-450a-9a44-06ecd244c0b7',
  'id': 1,
  'lastModified': '2020-11-18T09:14:53.011',
  'name': 'public',
  'meta': 'Item is completely described and operational.'},
 'type': {'@uuid': '1968baba-6b7b-4fff-a96c-99a9911abd6b',
  'id': 118,
  'created': '2025-05-19T16:26:48.945',
  'lastModified': '2025-05-19T16:26:48.947',
  'generalName': 'oxygen sensor',
  'systemName': 'oxygen_sensor',
  'description': 'An instrument that may be incorporated into a sensor package to measure dissolved oxygen concentrations in place in the field. ',
  'vocabulary': 'NERC',
  'vocableValue': 'https://vocab.nerc.ac.uk/collection/S04/current/S04276',
  'vocableGroup': {'@uuid': '85694c85-5aee-441f-a88a-a6bb8f1d0885',
   'id': 7,
   'created': '2024-09-04T09:04:10.581',
   'lastModified': '2025-07-11T15:02:05.167',
   'name': 'DeviceTypes',
   'systemName': 'DeviceTypes'}},
 'version': 1,
 'itemProperties': []}

Or the numeric identifier can be pasted. The results are identical.

In [6]:
a.item(code = 560)

{'@uuid': '972f7341-7524-40ac-ad5d-1ab2b0603fe1',
 'id': 560,
 'created': '2016-06-27T00:00:00',
 'lastModified': '2024-01-17T19:17:13.759',
 'code': 'vessel:mya_ii:fb_741202:optode_9999a',
 'shortName': 'Optode_9999a',
 'longName': 'Optode',
 'description': 'The Aanderaa oxygen optodes are based on the ability of selected substances to act as dynamic uorescence quenchers. The uorescent indicator is a special platinum porphyrin complex embedded in a gas permeable foil that is exposed to the surrounding water. A black optical isolation coating protects the complex from sunlight and uorescent particles in the water. This sensing foil is attached to a window providing optical access for the measuring system from inside awatertight housing.Thefoilisexcitedbymodulated blue light, and the phase of a returned red light is measured. By linearizing and temperature compensating, with an incorporated temperature sensor, the absolute O2 concentration can be determined.',
 'model': 'OXYGEN OPTODE 4835',
 'manufacturer': 'Aanderaa',
 'serialNumber': '9999a',
 'inventoryNumber': '',
 'citation': '10013/sensor.51ea3572-e557-4b2b-a202-3b749a87bf84',
 'parentId': 508,
 'status': {'@uuid': 'a080ff68-30b2-450a-9a44-06ecd244c0b7',
  'id': 1,
  'lastModified': '2020-11-18T09:14:53.011',
  'name': 'public',
  'meta': 'Item is completely described and operational.'},
 'type': {'@uuid': '1968baba-6b7b-4fff-a96c-99a9911abd6b',
  'id': 118,
  'created': '2025-05-19T16:26:48.945',
  'lastModified': '2025-05-19T16:26:48.947',
  'generalName': 'oxygen sensor',
  'systemName': 'oxygen_sensor',
  'description': 'An instrument that may be incorporated into a sensor package to measure dissolved oxygen concentrations in place in the field. ',
  'vocabulary': 'NERC',
  'vocableValue': 'https://vocab.nerc.ac.uk/collection/S04/current/S04276',
  'vocableGroup': {'@uuid': '85694c85-5aee-441f-a88a-a6bb8f1d0885',
   'id': 7,
   'created': '2024-09-04T09:04:10.581',
   'lastModified': '2025-07-11T15:02:05.167',
   'name': 'DeviceTypes',
   'systemName': 'DeviceTypes'}},
 'version': 1,
 'itemProperties': []}


Be aware that only the first occurence of an information is printed entirely. The remaining occurences are references. The parameters can be retrieved as follows:

In [7]:
a.parameters(urn)[1:4]

[{'@uuid': 'df34ddf1-9b54-11ef-9e4a-005056a5aa32',
  'id': 651,
  'name': 'Oxygen',
  'shortName': 'oxygen',
  'unit': 'acbd5aa2-df76-4194-843c-e05018798220',
  'type': 'c32366c1-87c1-4fee-8bd1-42420a01c6aa',
  'properties': [],
  'urn': 'vessel:mya_ii:fb_741202:optode_9999a:oxygen'},
 {'@uuid': 'df34df3b-9b54-11ef-9e4a-005056a5aa32',
  'id': 652,
  'name': 'Saturation',
  'shortName': 'saturation',
  'unit': {'@uuid': 'b8e0d45f-4490-497d-bbca-17831378ffe6',
   'id': 12,
   'code': '%',
   'name': 'percent',
   'typicalUse': 'concentration, amount, quantity, quality',
   'ucum': '%',
   'mathML': '{%}',
   'visible': True},
  'type': {'@uuid': '2b17bdd5-26a6-400c-b26d-086ca7e4f8ad',
   'id': 221,
   'created': '2025-05-19T16:27:37.715',
   'lastModified': '2025-05-19T16:27:37.716',
   'generalName': 'saturation',
   'systemName': 'saturation',
   'description': 'A ratio of the measured concentration of a dissolved element or compund in the water to the maximum amount of that element or compound that will dissolve in the water at that temperature and pressure under stable equilibrium',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/S06/current/S0600051',
   'vocableGroup': 'b876cf1e-b073-4569-9ab6-8fa33ff3108c'},
  'properties': [],
  'urn': 'vessel:mya_ii:fb_741202:optode_9999a:saturation'},
 {'@uuid': 'dfcb16bb-9b54-11ef-9e4a-005056a5aa32',
  'id': 102121,
  'name': 'Saturation QF',
  'shortName': 'saturation_qf',
  'comment': '\n',
  'unit': 'b8e0d45f-4490-497d-bbca-17831378ffe6',
  'type': '2b17bdd5-26a6-400c-b26d-086ca7e4f8ad',
  'properties': [],
  'urn': 'vessel:mya_ii:fb_741202:optode_9999a:saturation_qf'}]


Output list of all events, here restricted to list items 1-4 (to avoid excessive output):

In [8]:
a.events(urn)[1:3]

[{'@uuid': 'f10d83d1-9ea7-4f13-8644-44aa8311344b',
  'id': 43279,
  'startDate': '2020-08-31T09:14:00',
  'endDate': '2020-08-31T09:22:00',
  'latitude': 53.9048,
  'longitude': 8.7049,
  'elevation': 13.0,
  'label': 'MOSES Sternfahrt 5 M-1',
  'description': 'surface (1 m) bottom (13 m)',
  'type': {'@uuid': '047a4f46-020b-4187-808a-6f245caebbc3',
   'id': 187,
   'created': '2025-05-19T16:27:24.495',
   'lastModified': '2025-05-19T16:27:24.496',
   'generalName': 'Deployment',
   'systemName': 'deployment',
   'description': 'A device is deployed, means it is in operational use. Deployment applies to small-scale vehicles and ship-operated devices, such as CTD rosettes, buoys, etc.. ',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/W03/current/W030002',
   'vocableGroup': '2ea05127-95fd-4f2d-aa68-82ea0283aaaf'}},
 {'@uuid': '9a83740d-1eba-4046-a780-b8f4c12c86ae',
  'id': 43280,
  'startDate': '2020-08-31T10:13:00',
  'endDate': '2020-08-31T10:21:00',
  'latitude': 53.9494,
  'longitude': 8.6563,
  'elevation': 14.0,
  'label': 'MOSES Sternfahrt 5 M-2',
  'description': 'surface (1 m) bottom (13 m)',
  'type': {'@uuid': '047a4f46-020b-4187-808a-6f245caebbc3',
   'id': 187,
   'created': '2025-05-19T16:27:24.495',
   'lastModified': '2025-05-19T16:27:24.496',
   'generalName': 'Deployment',
   'systemName': 'deployment',
   'description': 'A device is deployed, means it is in operational use. Deployment applies to small-scale vehicles and ship-operated devices, such as CTD rosettes, buoys, etc.. ',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/W03/current/W030002',
   'vocableGroup': '2ea05127-95fd-4f2d-aa68-82ea0283aaaf'}}]

In [9]:

a.events(456, geo = True)
#a.item(456)

https://registry.o2a-data.de/rest/v2/items/456/events?where=latitude>=-90;latitude<=90;longitude>=-180;longitude<=180

[{'@uuid': '1beb2252-094a-4a6c-a09a-1d59a3ac30ab',
  'id': 42979,
  'startDate': '2020-08-31T06:00:00',
  'endDate': '2020-09-03T22:00:00',
  'latitude': 54.453,
  'longitude': 7.2138,
  'elevation': 0.0,
  'label': 'MOSES Sternfahrt 5 mission',
  'description': 'Research vessels Mya II (AWI), Littorina (Geomar), and Ludwig Prandtl (HZG) take part in MOSES Sternfahrt 5. Aims of the cruise: i) to improve ship to ship communication and data/screen transfer, ii) to get a clear separation line between Weser and Elbe water in the German Bight with the help of the back-tracking model. All ships will criss-cross the expected separation line several times.',
  'type': {'@uuid': '78318577-0e23-4dfe-ad2b-bfe6cb23b9a7',
   'id': 182,
   'created': '2025-05-19T16:27:23.095',
   'lastModified': '2025-05-19T16:27:23.096',
   'generalName': 'Mission',
   'systemName': 'mission',
   'description': 'A Mission refers to the device&apos;s operation within a defined range of time and purpose.',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/G07/current/006',
   'vocableGroup': {'@uuid': '2ea05127-95fd-4f2d-aa68-82ea0283aaaf',
    'id': 8,
    'created': '2025-07-11T15:01:11.79',
    'lastModified': '2025-07-11T15:01:11.791',
    'name': 'Event Types',
    'systemName': 'EventTypes'}}},
 {'@uuid': 'f10d83d1-9ea7-4f13-8644-44aa8311344b',
  'id': 43279,
  'startDate': '2020-08-31T09:14:00',
  'endDate': '2020-08-31T09:22:00',
  'latitude': 53.9048,
  'longitude': 8.7049,
  'elevation': 13.0,
  'label': 'MOSES Sternfahrt 5 M-1',
  'description': 'surface (1 m) bottom (13 m)',
  'type': {'@uuid': '047a4f46-020b-4187-808a-6f245caebbc3',
   'id': 187,
   'created': '2025-05-19T16:27:24.495',
   'lastModified': '2025-05-19T16:27:24.496',
   'generalName': 'Deployment',
   'systemName': 'deployment',
   'description': 'A device is deployed, means it is in operational use. Deployment applies to small-scale vehicles and ship-operated devices, such as CTD rosettes, buoys, etc.. ',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/W03/current/W030002',
   'vocableGroup': '2ea05127-95fd-4f2d-aa68-82ea0283aaaf'}},
 {'@uuid': '9a83740d-1eba-4046-a780-b8f4c12c86ae',
  'id': 43280,
  'startDate': '2020-08-31T10:13:00',
  'endDate': '2020-08-31T10:21:00',
  'latitude': 53.9494,
  'longitude': 8.6563,
  'elevation': 14.0,
  'label': 'MOSES Sternfahrt 5 M-2',
  'description': 'surface (1 m) bottom (13 m)',
  'type': {'@uuid': '047a4f46-020b-4187-808a-6f245caebbc3',
   'id': 187,
   'created': '2025-05-19T16:27:24.495',
   'lastModified': '2025-05-19T16:27:24.496',
   'generalName': 'Deployment',
   'systemName': 'deployment',
   'description': 'A device is deployed, means it is in operational use. Deployment applies to small-scale vehicles and ship-operated devices, such as CTD rosettes, buoys, etc.. ',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/W03/current/W030002',
   'vocableGroup': '2ea05127-95fd-4f2d-aa68-82ea0283aaaf'}},
 {'@uuid': '39f78b5c-55ea-44bf-83fd-eb32325a7dfb',
  'id': 43281,
  'startDate': '2020-08-31T11:00:00',
  'endDate': '2020-08-31T11:09:00',
  'latitude': 53.97635,
  'longitude': 8.5548,
  'elevation': 11.0,
  'label': 'MOSES Sternfahrt 5 M-3',
  'description': 'surface (1 m) bottom (10 m) Vorbeifahrt MS Helgoland um 09:02',
  'type': {'@uuid': '047a4f46-020b-4187-808a-6f245caebbc3',
   'id': 187,
   'created': '2025-05-19T16:27:24.495',
   'lastModified': '2025-05-19T16:27:24.496',
   'generalName': 'Deployment',
   'systemName': 'deployment',
   'description': 'A device is deployed, means it is in operational use. Deployment applies to small-scale vehicles and ship-operated devices, such as CTD rosettes, buoys, etc.. ',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/W03/current/W030002',
   'vocableGroup': '2ea05127-95fd-4f2d-aa68-82ea0283aaaf'}},
 {'@uuid': '6022068f-ddbf-4c78-8a37-852e0866a812',
  'id': 43282,
  'startDate': '2020-08-31T11:56:00',
  'endDate': '2020-08-31T12:05:00',
  'latitude': 53.99955,
  'longitude': 8.38115,
  'elevation': 12.5,
  'label': 'MOSES Sternfahrt 5 M-4',
  'description': 'surface (1 m) bottom (11 m)',
  'type': {'@uuid': '047a4f46-020b-4187-808a-6f245caebbc3',
   'id': 187,
   'created': '2025-05-19T16:27:24.495',
   'lastModified': '2025-05-19T16:27:24.496',
   'generalName': 'Deployment',
   'systemName': 'deployment',
   'description': 'A device is deployed, means it is in operational use. Deployment applies to small-scale vehicles and ship-operated devices, such as CTD rosettes, buoys, etc.. ',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/W03/current/W030002',
   'vocableGroup': '2ea05127-95fd-4f2d-aa68-82ea0283aaaf'}},
 {'@uuid': '2d60b28f-174d-4d5c-a5bb-f58703ad97d8',
  'id': 43283,
  'startDate': '2020-08-31T12:31:00',
  'endDate': '2020-08-31T12:39:00',
  'latitude': 54.0216,
  'longitude': 8.3036,
  'elevation': 10.5,
  'label': 'MOSES Sternfahrt 5 M-5',
  'description': 'surface (1 m) bottom (10 m)',
  'type': {'@uuid': '047a4f46-020b-4187-808a-6f245caebbc3',
   'id': 187,
   'created': '2025-05-19T16:27:24.495',
   'lastModified': '2025-05-19T16:27:24.496',
   'generalName': 'Deployment',
   'systemName': 'deployment',
   'description': 'A device is deployed, means it is in operational use. Deployment applies to small-scale vehicles and ship-operated devices, such as CTD rosettes, buoys, etc.. ',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/W03/current/W030002',
   'vocableGroup': '2ea05127-95fd-4f2d-aa68-82ea0283aaaf'}},
 {'@uuid': '790eea00-73f1-448c-9c95-ab106b6426bb',
  'id': 43284,
  'startDate': '2020-08-31T13:28:00',
  'endDate': '2020-08-31T13:37:00',
  'latitude': 54.0792,
  'longitude': 8.13985,
  'elevation': 20.0,
  'label': 'MOSES Sternfahrt 5 M-6',
  'description': 'surface (1 m) bottom (20 m)',
  'type': {'@uuid': '047a4f46-020b-4187-808a-6f245caebbc3',
   'id': 187,
   'created': '2025-05-19T16:27:24.495',
   'lastModified': '2025-05-19T16:27:24.496',
   'generalName': 'Deployment',
   'systemName': 'deployment',
   'description': 'A device is deployed, means it is in operational use. Deployment applies to small-scale vehicles and ship-operated devices, such as CTD rosettes, buoys, etc.. ',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/W03/current/W030002',
   'vocableGroup': '2ea05127-95fd-4f2d-aa68-82ea0283aaaf'}},
 {'@uuid': 'dc515110-197d-48db-97cf-c9a590426a4b',
  'id': 43285,
  'startDate': '2020-08-31T14:22:00',
  'endDate': '2020-08-31T14:33:00',
  'latitude': 54.11095,
  'longitude': 8.05485,
  'elevation': 24.5,
  'label': 'MOSES Sternfahrt 5 M-7',
  'description': 'surface (1 m) bottom (20 m)',
  'type': {'@uuid': '047a4f46-020b-4187-808a-6f245caebbc3',
   'id': 187,
   'created': '2025-05-19T16:27:24.495',
   'lastModified': '2025-05-19T16:27:24.496',
   'generalName': 'Deployment',
   'systemName': 'deployment',
   'description': 'A device is deployed, means it is in operational use. Deployment applies to small-scale vehicles and ship-operated devices, such as CTD rosettes, buoys, etc.. ',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/W03/current/W030002',
   'vocableGroup': '2ea05127-95fd-4f2d-aa68-82ea0283aaaf'}},
 {'@uuid': 'df9aa67a-fdea-4f96-ae72-265696512eba',
  'id': 43286,
  'startDate': '2020-08-31T14:56:00',
  'endDate': '2020-08-31T15:06:00',
  'latitude': 54.1395,
  'longitude': 7.9763,
  'elevation': 40.5,
  'label': 'MOSES Sternfahrt 5 M-8',
  'description': 'surface (1 m) bottom (20 m)',
  'type': {'@uuid': '047a4f46-020b-4187-808a-6f245caebbc3',
   'id': 187,
   'created': '2025-05-19T16:27:24.495',
   'lastModified': '2025-05-19T16:27:24.496',
   'generalName': 'Deployment',
   'systemName': 'deployment',
   'description': 'A device is deployed, means it is in operational use. Deployment applies to small-scale vehicles and ship-operated devices, such as CTD rosettes, buoys, etc.. ',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/W03/current/W030002',
   'vocableGroup': '2ea05127-95fd-4f2d-aa68-82ea0283aaaf'}},
 {'@uuid': 'cfacaf4c-62ae-48ad-8771-649d5cc97bd7',
  'id': 43287,
  'startDate': '2020-09-01T08:54:00',
  'endDate': '2020-09-01T09:09:00',
  'latitude': 54.14835,
  'longitude': 7.9306,
  'elevation': 46.5,
  'label': 'MOSES Sternfahrt 5 M-9',
  'description': 'surface (1 m) bottom (20 m)',
  'type': {'@uuid': '047a4f46-020b-4187-808a-6f245caebbc3',
   'id': 187,
   'created': '2025-05-19T16:27:24.495',
   'lastModified': '2025-05-19T16:27:24.496',
   'generalName': 'Deployment',
   'systemName': 'deployment',
   'description': 'A device is deployed, means it is in operational use. Deployment applies to small-scale vehicles and ship-operated devices, such as CTD rosettes, buoys, etc.. ',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/W03/current/W030002',
   'vocableGroup': '2ea05127-95fd-4f2d-aa68-82ea0283aaaf'}},
 {'@uuid': '64b89027-4eb4-4993-9f79-c98b996d51cb',
  'id': 43288,
  'startDate': '2020-09-01T10:21:00',
  'endDate': '2020-09-01T10:30:00',
  'latitude': 54.003600000000006,
  'longitude': 8.00705,
  'elevation': 31.0,
  'label': 'MOSES Sternfahrt 5 M-10',
  'description': 'surface (1 m) bottom (20 m)',
  'type': {'@uuid': '047a4f46-020b-4187-808a-6f245caebbc3',
   'id': 187,
   'created': '2025-05-19T16:27:24.495',
   'lastModified': '2025-05-19T16:27:24.496',
   'generalName': 'Deployment',
   'systemName': 'deployment',
   'description': 'A device is deployed, means it is in operational use. Deployment applies to small-scale vehicles and ship-operated devices, such as CTD rosettes, buoys, etc.. ',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/W03/current/W030002',
   'vocableGroup': '2ea05127-95fd-4f2d-aa68-82ea0283aaaf'}},
 {'@uuid': '93966b09-ec1c-42f1-b34a-6e0f41da13c4',
  'id': 43289,
  'startDate': '2020-09-01T11:03:00',
  'endDate': '2020-09-01T11:12:00',
  'latitude': 53.919200000000004,
  'longitude': 8.0048,
  'elevation': 13.5,
  'label': 'MOSES Sternfahrt 5 M-11',
  'description': 'surface (1 m) bottom (15 m)',
  'type': {'@uuid': '047a4f46-020b-4187-808a-6f245caebbc3',
   'id': 187,
   'created': '2025-05-19T16:27:24.495',
   'lastModified': '2025-05-19T16:27:24.496',
   'generalName': 'Deployment',
   'systemName': 'deployment',
   'description': 'A device is deployed, means it is in operational use. Deployment applies to small-scale vehicles and ship-operated devices, such as CTD rosettes, buoys, etc.. ',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/W03/current/W030002',
   'vocableGroup': '2ea05127-95fd-4f2d-aa68-82ea0283aaaf'}},
 {'@uuid': 'e1494671-757a-415a-85d0-27503b8bc67f',
  'id': 43290,
  'startDate': '2020-09-01T11:35:00',
  'endDate': '2020-09-01T11:44:00',
  'latitude': 53.857749999999996,
  'longitude': 8.0054,
  'elevation': 19.0,
  'label': 'MOSES Sternfahrt 5 M-12',
  'description': 'surface (1 m) bottom (20 m)',
  'type': {'@uuid': '047a4f46-020b-4187-808a-6f245caebbc3',
   'id': 187,
   'created': '2025-05-19T16:27:24.495',
   'lastModified': '2025-05-19T16:27:24.496',
   'generalName': 'Deployment',
   'systemName': 'deployment',
   'description': 'A device is deployed, means it is in operational use. Deployment applies to small-scale vehicles and ship-operated devices, such as CTD rosettes, buoys, etc.. ',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/W03/current/W030002',
   'vocableGroup': '2ea05127-95fd-4f2d-aa68-82ea0283aaaf'}},
 {'@uuid': '38da5482-b974-4499-b765-e0707bc53f95',
  'id': 43291,
  'startDate': '2020-09-01T12:17:00',
  'endDate': '2020-09-01T12:26:00',
  'latitude': 53.79555,
  'longitude': 8.123899999999999,
  'elevation': 17.0,
  'label': 'MOSES Sternfahrt 5 M-13',
  'description': 'surface (1 m) bottom (20 m)',
  'type': {'@uuid': '047a4f46-020b-4187-808a-6f245caebbc3',
   'id': 187,
   'created': '2025-05-19T16:27:24.495',
   'lastModified': '2025-05-19T16:27:24.496',
   'generalName': 'Deployment',
   'systemName': 'deployment',
   'description': 'A device is deployed, means it is in operational use. Deployment applies to small-scale vehicles and ship-operated devices, such as CTD rosettes, buoys, etc.. ',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/W03/current/W030002',
   'vocableGroup': '2ea05127-95fd-4f2d-aa68-82ea0283aaaf'}},
 {'@uuid': '2e806e71-f96b-42dd-a7ad-baaa668a7d85',
  'id': 43292,
  'startDate': '2020-09-01T13:02:00',
  'endDate': '2020-09-01T13:11:00',
  'latitude': 53.72625,
  'longitude': 8.245550000000001,
  'elevation': 15.5,
  'label': 'MOSES Sternfahrt 5 M-14',
  'description': 'surface (1 m) bottom (15 m)',
  'type': {'@uuid': '047a4f46-020b-4187-808a-6f245caebbc3',
   'id': 187,
   'created': '2025-05-19T16:27:24.495',
   'lastModified': '2025-05-19T16:27:24.496',
   'generalName': 'Deployment',
   'systemName': 'deployment',
   'description': 'A device is deployed, means it is in operational use. Deployment applies to small-scale vehicles and ship-operated devices, such as CTD rosettes, buoys, etc.. ',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/W03/current/W030002',
   'vocableGroup': '2ea05127-95fd-4f2d-aa68-82ea0283aaaf'}},
 {'@uuid': '6973afc6-45da-4a53-9363-4ae7f5ec1a5b',
  'id': 43293,
  'startDate': '2020-09-01T13:46:00',
  'endDate': '2020-09-01T13:54:00',
  'latitude': 53.6697,
  'longitude': 8.372050000000002,
  'elevation': 16.0,
  'label': 'MOSES Sternfahrt 5 M-15',
  'description': 'surface (1 m) bottom (15 m)',
  'type': {'@uuid': '047a4f46-020b-4187-808a-6f245caebbc3',
   'id': 187,
   'created': '2025-05-19T16:27:24.495',
   'lastModified': '2025-05-19T16:27:24.496',
   'generalName': 'Deployment',
   'systemName': 'deployment',
   'description': 'A device is deployed, means it is in operational use. Deployment applies to small-scale vehicles and ship-operated devices, such as CTD rosettes, buoys, etc.. ',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/W03/current/W030002',
   'vocableGroup': '2ea05127-95fd-4f2d-aa68-82ea0283aaaf'}},
 {'@uuid': 'e414c8d9-b3d7-46f9-9b5d-dadbd479f1c3',
  'id': 43294,
  'startDate': '2020-09-01T14:34:00',
  'endDate': '2020-09-01T14:42:00',
  'latitude': 53.603449999999995,
  'longitude': 8.4969,
  'elevation': 12.5,
  'label': 'MOSES Sternfahrt 5 M-16',
  'description': 'surface (1 m) bottom (15 m)',
  'type': {'@uuid': '047a4f46-020b-4187-808a-6f245caebbc3',
   'id': 187,
   'created': '2025-05-19T16:27:24.495',
   'lastModified': '2025-05-19T16:27:24.496',
   'generalName': 'Deployment',
   'systemName': 'deployment',
   'description': 'A device is deployed, means it is in operational use. Deployment applies to small-scale vehicles and ship-operated devices, such as CTD rosettes, buoys, etc.. ',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/W03/current/W030002',
   'vocableGroup': '2ea05127-95fd-4f2d-aa68-82ea0283aaaf'}},
 {'@uuid': '025fdf88-6669-4984-9493-4c6a521b8d66',
  'id': 43295,
  'startDate': '2020-09-02T09:30:00',
  'endDate': '2020-09-02T09:40:00',
  'latitude': 53.6736,
  'longitude': 8.38025,
  'elevation': 10.5,
  'label': 'MOSES Sternfahrt 5 M-17',
  'description': 'surface (1 m) bottom (10 m)',
  'type': {'@uuid': '047a4f46-020b-4187-808a-6f245caebbc3',
   'id': 187,
   'created': '2025-05-19T16:27:24.495',
   'lastModified': '2025-05-19T16:27:24.496',
   'generalName': 'Deployment',
   'systemName': 'deployment',
   'description': 'A device is deployed, means it is in operational use. Deployment applies to small-scale vehicles and ship-operated devices, such as CTD rosettes, buoys, etc.. ',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/W03/current/W030002',
   'vocableGroup': '2ea05127-95fd-4f2d-aa68-82ea0283aaaf'}},
 {'@uuid': '160f17e0-2525-477a-9cbc-ddbeeb8ba1a8',
  'id': 43296,
  'startDate': '2020-09-02T10:32:00',
  'endDate': '2020-09-02T10:41:00',
  'latitude': 53.7341,
  'longitude': 8.25765,
  'elevation': 10.5,
  'label': 'MOSES Sternfahrt 5 M-18',
  'description': 'surface (1 m) bottom (10 m)',
  'type': {'@uuid': '047a4f46-020b-4187-808a-6f245caebbc3',
   'id': 187,
   'created': '2025-05-19T16:27:24.495',
   'lastModified': '2025-05-19T16:27:24.496',
   'generalName': 'Deployment',
   'systemName': 'deployment',
   'description': 'A device is deployed, means it is in operational use. Deployment applies to small-scale vehicles and ship-operated devices, such as CTD rosettes, buoys, etc.. ',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/W03/current/W030002',
   'vocableGroup': '2ea05127-95fd-4f2d-aa68-82ea0283aaaf'}},
 {'@uuid': 'eae98efb-d9f2-40f7-8d34-6acc4c13b64c',
  'id': 43297,
  'startDate': '2020-09-02T11:32:00',
  'endDate': '2020-09-02T11:40:00',
  'latitude': 53.8064,
  'longitude': 8.14435,
  'elevation': 9.0,
  'label': 'MOSES Sternfahrt 5 M-19',
  'description': 'surface (1 m) bottom (10 m)',
  'type': {'@uuid': '047a4f46-020b-4187-808a-6f245caebbc3',
   'id': 187,
   'created': '2025-05-19T16:27:24.495',
   'lastModified': '2025-05-19T16:27:24.496',
   'generalName': 'Deployment',
   'systemName': 'deployment',
   'description': 'A device is deployed, means it is in operational use. Deployment applies to small-scale vehicles and ship-operated devices, such as CTD rosettes, buoys, etc.. ',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/W03/current/W030002',
   'vocableGroup': '2ea05127-95fd-4f2d-aa68-82ea0283aaaf'}},
 {'@uuid': '33032342-04fa-4ea9-b033-be5cb61d5db1',
  'id': 43298,
  'startDate': '2020-09-02T12:25:00',
  'endDate': '2020-09-02T12:35:00',
  'latitude': 53.85895,
  'longitude': 8.006,
  'elevation': 20.0,
  'label': 'MOSES Sternfahrt 5 M-20',
  'description': 'surface (1 m) bottom (20 m)',
  'type': {'@uuid': '047a4f46-020b-4187-808a-6f245caebbc3',
   'id': 187,
   'created': '2025-05-19T16:27:24.495',
   'lastModified': '2025-05-19T16:27:24.496',
   'generalName': 'Deployment',
   'systemName': 'deployment',
   'description': 'A device is deployed, means it is in operational use. Deployment applies to small-scale vehicles and ship-operated devices, such as CTD rosettes, buoys, etc.. ',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/W03/current/W030002',
   'vocableGroup': '2ea05127-95fd-4f2d-aa68-82ea0283aaaf'}},
 {'@uuid': '3cea71c3-776e-42d2-ae66-6cf99c2b7df9',
  'id': 43299,
  'startDate': '2020-09-02T12:56:00',
  'endDate': '2020-09-02T13:05:00',
  'latitude': 53.863150000000005,
  'longitude': 7.9336,
  'elevation': 21.0,
  'label': 'MOSES Sternfahrt 5 M-21',
  'description': 'surface (1 m) bottom (20 m)',
  'type': {'@uuid': '047a4f46-020b-4187-808a-6f245caebbc3',
   'id': 187,
   'created': '2025-05-19T16:27:24.495',
   'lastModified': '2025-05-19T16:27:24.496',
   'generalName': 'Deployment',
   'systemName': 'deployment',
   'description': 'A device is deployed, means it is in operational use. Deployment applies to small-scale vehicles and ship-operated devices, such as CTD rosettes, buoys, etc.. ',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/W03/current/W030002',
   'vocableGroup': '2ea05127-95fd-4f2d-aa68-82ea0283aaaf'}},
 {'@uuid': 'b518a071-f3db-4ec3-b700-8401a16835cb',
  'id': 43300,
  'startDate': '2020-09-02T13:52:00',
  'endDate': '2020-09-02T14:02:00',
  'latitude': 53.850300000000004,
  'longitude': 7.74005,
  'elevation': 22.0,
  'label': 'MOSES Sternfahrt 5 M-22',
  'description': 'surface (1 m) bottom (20 m)',
  'type': {'@uuid': '047a4f46-020b-4187-808a-6f245caebbc3',
   'id': 187,
   'created': '2025-05-19T16:27:24.495',


Checking who is in charge (or at least knows who is). Again, this works either with the complete urn or by submitting the id:

In [10]:

a.contacts(8767)

[{'@uuid': 'c6f95b82-9b54-11ef-9e4a-005056a5aa32',
  'id': 21453,
  'contact': {'@uuid': '3943c7f0-39d9-47b8-b2d9-9b2e6d48299b',
   'id': 21,
   'created': '2025-07-17T09:33:20.029',
   'lastModified': '2025-07-17T10:03:32.516',
   'firstName': 'Philipp',
   'lastName': 'Fischer',
   'email': 'philipp.fischer@awi.de',
   'telephone': '+49(4725)819-3344',
   'postalCode': '27570',
   'city': 'Bremerhaven',
   'administrativeArea': '',
   'country': 'Germany',
   'companyName': 'Alfred Wegener Institute for Polar and Marine Research',
   'ror': 'https://ror.org/032e6b942'},
  'role': {'@uuid': '9e7a0ba6-cea4-4f45-9146-38311bde9395',
   'id': 5,
   'created': '2024-10-29T15:53:43.015',
   'lastModified': '2025-05-19T16:26:04.831',
   'generalName': 'Principal Investigator',
   'systemName': 'principal_investigator',
   'description': 'Key party responsible for gathering information and conducting research.',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/G04/current/008',
   'vocableGroup': {'@uuid': 'aa18bd44-2a65-4e43-bdd8-d7400467116b',
    'id': 2,
    'created': '2025-07-11T15:01:39.63',
    'lastModified': '2025-07-11T15:01:39.63',
    'name': 'Contact Roles',
    'systemName': 'ContactRoles'}}},
 {'@uuid': 'c6f95bce-9b54-11ef-9e4a-005056a5aa32',
  'id': 21454,
  'contact': {'@uuid': '3943c7f0-39d9-47b8-b2d9-9b2e6d48299b',
   'id': 21,
   'created': '2025-07-17T09:33:20.029',
   'lastModified': '2025-07-17T10:03:32.516',
   'firstName': 'Philipp',
   'lastName': 'Fischer',
   'email': 'philipp.fischer@awi.de',
   'telephone': '+49(4725)819-3344',
   'postalCode': '27570',
   'city': 'Bremerhaven',
   'administrativeArea': '',
   'country': 'Germany',
   'companyName': 'Alfred Wegener Institute for Polar and Marine Research',
   'ror': 'https://ror.org/032e6b942'},
  'role': {'@uuid': '74fd3d66-64db-448a-9bdf-33f16c9825eb',
   'id': 239,
   'created': '2024-10-28T18:42:15.736',
   'lastModified': '2025-05-19T16:27:47.833',
   'generalName': 'Editor',
   'systemName': 'editor',
   'description': 'Party who reviewed or modified the resource to improve the content.',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/G04/current/015',
   'vocableGroup': 'aa18bd44-2a65-4e43-bdd8-d7400467116b'}},
 {'@uuid': 'c6f95c1b-9b54-11ef-9e4a-005056a5aa32',
  'id': 21455,
  'contact': {'@uuid': '775da600-f48b-4ee3-8c4f-20acfbe95d30',
   'id': 169,
   'created': '2025-07-17T09:53:31.878',
   'lastModified': '2025-07-17T10:04:41.396',
   'firstName': 'Ingeborg',
   'lastName': 'Bussmann',
   'email': 'ingeborg.bussmann@awi.de',
   'orcid': '',
   'telephone': '+49(4725)819-3230',
   'postalCode': '27570',
   'city': 'Bremerhaven',
   'administrativeArea': '',
   'country': 'Germany',
   'companyName': 'Alfred Wegener Institute for Polar and Marine Research',
   'ror': 'https://ror.org/032e6b942'},
  'role': {'@uuid': '9e7a0ba6-cea4-4f45-9146-38311bde9395',
   'id': 5,
   'created': '2024-10-29T15:53:43.015',
   'lastModified': '2025-05-19T16:26:04.831',
   'generalName': 'Principal Investigator',
   'systemName': 'principal_investigator',
   'description': 'Key party responsible for gathering information and conducting research.',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/G04/current/008',
   'vocableGroup': {'@uuid': 'aa18bd44-2a65-4e43-bdd8-d7400467116b',
    'id': 2,
    'created': '2025-07-11T15:01:39.63',
    'lastModified': '2025-07-11T15:01:39.63',
    'name': 'Contact Roles',
    'systemName': 'ContactRoles'}}},
 {'@uuid': 'c6f95b33-9b54-11ef-9e4a-005056a5aa32',
  'id': 21452,
  'contact': {'@uuid': '3e95c8b7-15e1-499b-b2eb-3c3884e32361',
   'id': 442,
   'created': '2025-06-20T06:29:45.85',
   'lastModified': '2025-06-20T07:03:40.01',
   'firstName': 'Norbert',
   'lastName': 'Anselm',
   'email': 'norbert.anselm@awi.de',
   'orcid': 'https://orcid.org/0000-0003-0367-6850',
   'telephone': '+49(471)4831-1095',
   'postalCode': '27570',
   'city': 'Bremerhaven',
   'administrativeArea': 'string',
   'country': 'Germany',
   'companyName': 'Alfred Wegener Institute for Polar and Marine Research',
   'ror': 'https://ror.org/032e6b942'},
  'role': {'@uuid': '74fd3d66-64db-448a-9bdf-33f16c9825eb',
   'id': 239,
   'created': '2024-10-28T18:42:15.736',
   'lastModified': '2025-05-19T16:27:47.833',
   'generalName': 'Editor',
   'systemName': 'editor',
   'description': 'Party who reviewed or modified the resource to improve the content.',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/G04/current/015',
   'vocableGroup': 'aa18bd44-2a65-4e43-bdd8-d7400467116b'}},
 {'@uuid': 'c6f95c69-9b54-11ef-9e4a-005056a5aa32',
  'id': 21456,
  'contact': {'@uuid': '3d98db93-39f9-40f2-b7fd-276e4d4deb78',
   'id': 635,
   'created': '2025-07-17T09:53:46.623',
   'lastModified': '2025-07-17T10:06:08.898',
   'firstName': 'Lea',
   'lastName': 'Happel',
   'email': 'lea.happel@awi.de',
   'orcid': '',
   'telephone': '+49(4725)819-3149',
   'postalCode': '27570',
   'city': 'Bremerhaven',
   'administrativeArea': '',
   'country': 'Germany',
   'companyName': 'Alfred Wegener Institute for Polar and Marine Research',
   'ror': 'https://ror.org/032e6b942'},
  'role': {'@uuid': '74fd3d66-64db-448a-9bdf-33f16c9825eb',
   'id': 239,
   'created': '2024-10-28T18:42:15.736',
   'lastModified': '2025-05-19T16:27:47.833',
   'generalName': 'Editor',
   'systemName': 'editor',
   'description': 'Party who reviewed or modified the resource to improve the content.',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/G04/current/015',
   'vocableGroup': 'aa18bd44-2a65-4e43-bdd8-d7400467116b'}}]


What items are mounted/attached to the respective item.

In [11]:
a.subitems(456)

[{'@uuid': '4803a9af-a7be-4e81-9556-b5f697e8d6bf',
  'id': 508,
  'created': '2016-06-14T00:00:00',
  'lastModified': '2024-01-17T19:17:14.011',
  'code': 'vessel:mya_ii:fb_741202',
  'shortName': 'FB_741202',
  'longName': 'Ferrybox Mya II',
  'description': 'The 4H FerryBox is an autonomous, low maintenance mertrology system which has been developed especially for permanent deployment on ships, metrology platforms and river measurement points. Due to its special architecture, the system is able to link a multitude of sensors and automatic analysis devices and even perform measurements in difficult media (such as sea water or bubbling water etc.). The entire sensor system is an integral part of the anti-fouling concept whereby the maintenance requirement is held to a minimum. ',
  'model': '4H Ferrybox',
  'manufacturer': '4H-Jena Engineering',
  'serialNumber': '741202',
  'inventoryNumber': '',
  'citation': '10013/sensor.1cde5be5-4783-4252-87d2-cf29cd1f7b80',
  'parentId': 456,
  'status': {'@uuid': 'a080ff68-30b2-450a-9a44-06ecd244c0b7',
   'id': 1,
   'lastModified': '2020-11-18T09:14:53.011',
   'name': 'public',
   'meta': 'Item is completely described and operational.'},
  'type': {'@uuid': 'a3083189-c77c-47f4-8ef5-02b72deb5bcb',
   'id': 199,
   'lastModified': '2022-09-14T10:12:33.445',
   'generalName': 'small scale facility',
   'systemName': 'small_scale_facility',
   'description': '',
   'vocabulary': 'AWI',
   'vocableValue': 'AWI',
   'vocableGroup': {'@uuid': '85694c85-5aee-441f-a88a-a6bb8f1d0885',
    'id': 7,
    'created': '2024-09-04T09:04:10.581',
    'lastModified': '2025-07-11T15:02:05.167',
    'name': 'DeviceTypes',
    'systemName': 'DeviceTypes'}},
  'version': 1},
 {'@uuid': 'ce1a69cc-de59-456f-adcf-f9f7640dd2fe',
  'id': 576,
  'created': '2016-07-18T00:00:00',
  'lastModified': '2024-01-17T19:17:14.077',
  'code': 'vessel:mya_ii:motion',
  'shortName': 'Motion',
  'longName': 'GPS-Receiver F185',
  'description': 'The F180® series is a range of GPS aided attitude and positioning systems that provide high quality and precise reference data for a number of marine applications including multibeam surveys and dynamic positioning projects. Blending together GNSS information with an inertial engine, the F180® series outputs Kalman filtered heading, position, heave, pitch and roll variables even in the most demanding of offshore conditions.',
  'model': 'F185',
  'manufacturer': 'Coda Octopus',
  'serialNumber': 'F0712185',
  'inventoryNumber': '',
  'citation': '10013/sensor.f790453d-f295-411a-bcd0-95d97f476cac',
  'parentId': 456,
  'status': 'a080ff68-30b2-450a-9a44-06ecd244c0b7',
  'type': {'@uuid': '7406ce34-4b6e-4258-9cce-19a4b68661af',
   'id': 147,
   'created': '2025-05-19T16:27:05.131',
   'lastModified': '2025-05-19T16:27:05.132',
   'generalName': 'satellite positioning system',
   'systemName': 'satellite_positioning_system',
   'description': 'A network of statellites that generate signals that allow a receiver to determine its position such as GPS.',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/L05/current/301',
   'vocableGroup': '85694c85-5aee-441f-a88a-a6bb8f1d0885'},
  'version': 3},
 {'@uuid': 'b0638487-abb2-42e7-808c-27562852029b',
  'id': 1225,
  'lastModified': '2024-01-17T19:17:14.149',
  'code': 'vessel:mya_ii:dgps',
  'shortName': 'DGPS',
  'longName': 'GPS-Receiver GP-150',
  'description': 'FURUNO GP150 is a GPS navigator designed for the SOLAS ships according to the GPS performance standard IMO Res MSC.112(73) and associated IEC standards effective on and after July 1, 2003. It is a highly reliable standalone EPFS (electronic position fixing system) that feeds positioning information to AIS, Radar, VDR, VideoPlotter, Autopilot, Echo Sounder and Sonar.',
  'model': 'Navigator GP-150',
  'manufacturer': 'Furuno',
  'serialNumber': '',
  'inventoryNumber': '',
  'citation': '10013/sensor.b61bc9b7-56cd-4cc8-83fc-86796c15e262',
  'parentId': 456,
  'status': 'a080ff68-30b2-450a-9a44-06ecd244c0b7',
  'type': {'@uuid': '7406ce34-4b6e-4258-9cce-19a4b68661af',
   'id': 147,
   'created': '2025-05-19T16:27:05.131',
   'lastModified': '2025-05-19T16:27:05.132',
   'generalName': 'satellite positioning system',
   'systemName': 'satellite_positioning_system',
   'description': 'A network of statellites that generate signals that allow a receiver to determine its position such as GPS.',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/L05/current/301',
   'vocableGroup': '85694c85-5aee-441f-a88a-a6bb8f1d0885'},
  'version': 0},
 {'@uuid': '9a631296-510a-4b42-b0c4-0aec920b5b00',
  'id': 1312,
  'lastModified': '2024-01-17T19:17:14.21',
  'code': 'vessel:mya_ii:navlot',
  'shortName': 'navlot',
  'longName': 'Navigation Echosounder',
  'description': '',
  'model': 'Ultragraph 475d',
  'manufacturer': 'Fahrentholz GmbH',
  'serialNumber': '',
  'inventoryNumber': '',
  'citation': '10013/sensor.7e9e1a1a-f0c7-463d-8fda-4c11dea6d093',
  'parentId': 456,
  'status': 'a080ff68-30b2-450a-9a44-06ecd244c0b7',
  'type': {'@uuid': '062397bd-7864-4a07-a040-1d41d7b2fbda',
   'id': 219,
   'lastModified': '2020-11-18T09:16:20.751',
   'generalName': 'not assigned',
   'systemName': 'not_assigned',
   'description': 'not assigned',
   'vocabulary': 'AWI',
   'vocableValue': 'not assigned',
   'vocableGroup': '85694c85-5aee-441f-a88a-a6bb8f1d0885'},
  'version': 0},
 {'@uuid': 'e288223d-6840-48a7-b135-14d4a686a62a',
  'id': 2834,
  'lastModified': '2024-01-17T19:17:14.285',
  'code': 'vessel:mya_ii:myaseabeam',
  'shortName': 'myaseabeam',
  'longName': 'Seabeam 1185',
  'description': 'Multibeam echo sounder L3 Elac Seabeam 1185. This system operates with frequency of 180 kHz. ',
  'model': 'Seabeam 1185',
  'manufacturer': 'L3 Elac',
  'serialNumber': '143',
  'inventoryNumber': '',
  'citation': '10013/sensor.c9987534-aadd-44f7-9ba3-5f055f9948fe',
  'parentId': 456,
  'status': 'a080ff68-30b2-450a-9a44-06ecd244c0b7',
  'type': {'@uuid': '7bea66ac-bec1-414d-8210-126420577652',
   'id': 266,
   'created': '2025-05-19T16:28:01.571',
   'lastModified': '2025-05-19T16:28:01.571',
   'generalName': 'multi-beam echosounder',
   'systemName': 'multi_beam_echosounder',
   'description': 'Instruments that measure water depth along several tracks parallel to the platform track by timing pulses of sound reflected on the seafloor.',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/L05/current/157',
   'vocableGroup': '85694c85-5aee-441f-a88a-a6bb8f1d0885'},
  'version': 0},
 {'@uuid': '64e7ead3-8010-4558-a234-18ba6282d7af',
  'id': 2835,
  'lastModified': '2024-01-17T19:17:14.354',
  'code': 'vessel:mya_ii:adcp18818',
  'shortName': 'ADCP18818',
  'longName': 'ADCP Workhorse Mariner 600 kHz',
  'description': '',
  'model': 'WHMVM600-I',
  'manufacturer': 'Teledyne RDI',
  'serialNumber': '18818',
  'inventoryNumber': '',
  'citation': '10013/sensor.f19b9896-6294-4270-8f07-97180b4499d2',
  'parentId': 456,
  'status': 'a080ff68-30b2-450a-9a44-06ecd244c0b7',
  'type': {'@uuid': '1e4b1257-131f-465b-81d7-ede5e893db99',
   'id': 269,
   'created': '2025-05-19T16:28:04.759',
   'lastModified': '2025-05-19T16:28:04.76',
   'generalName': 'acoustic backscatter sensor',
   'systemName': 'acoustic_backscatter_sensor',
   'description': 'Instrument that measures the amount of sound energy transmitted into the water column returned to the instrument.',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/L05/current/183',
   'vocableGroup': '85694c85-5aee-441f-a88a-a6bb8f1d0885'},
  'version': 0},
 {'@uuid': '5ebb94bb-1417-4bbd-a656-675c021afde8',
  'id': 2838,
  'lastModified': '2024-01-17T19:17:14.426',
  'code': 'vessel:mya_ii:eml224',
  'shortName': 'eml224',
  'longName': 'Scipper EM Log 224 Compact',
  'description': '',
  'model': 'EML224 Compact',
  'manufacturer': 'Skipper',
  'serialNumber': '',
  'inventoryNumber': '',
  'citation': '10013/sensor.59d0751a-7a43-4167-9f88-9885e8e689e2',
  'parentId': 456,
  'status': 'a080ff68-30b2-450a-9a44-06ecd244c0b7',
  'type': {'@uuid': '2327dde7-a06f-40cf-85cf-a08991a3d0c4',
   'id': 289,
   'created': '2025-05-19T16:28:17.912',
   'lastModified': '2025-05-19T16:28:17.913',
   'generalName': 'speed log',
   'systemName': 'speed_log',
   'description': 'Instrument that measures current speed and direction at a single depth.',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/L05/current/114',
   'vocableGroup': '85694c85-5aee-441f-a88a-a6bb8f1d0885'},
  'version': 0},
 {'@uuid': 'e5ef6e37-3545-42f8-a23b-f45c622a2cf7',
  'id': 2868,
  'lastModified': '2024-01-17T19:17:14.492',
  'code': 'vessel:mya_ii:seasunctd778',
  'shortName': 'SeaSunCTD778',
  'longName': 'Sea and Sun CTD',
  'description': 'The CTD90M memory probe is a microprocessor controlled multiparameter probe for precise online measurements as well as for self-contained operation in deep and shallow water. Apart of the CTD sensors it is possible to interface a number of chemical, physical and optical sensors and instruments. The housing of the probe is pressure resistant up to 500m depth, the maximum allowable operation depth depends on the sensors line-up. In spite of its relative big size the standard CTD has a weight of approximately 4.5kg due to the fact that it is completely made of titanium. The housing is inert against nearly all chemical compounds (except hydrofluoric acid) and absolutely corrosion free.',
  'model': 'CTD90M',
  'manufacturer': 'Sea and Sun Technology GmbH',
  'serialNumber': '778',
  'inventoryNumber': '',
  'citation': '10013/sensor.3b4a7f73-18fc-4679-98e0-25123eda21e8',
  'parentId': 456,
  'status': 'a080ff68-30b2-450a-9a44-06ecd244c0b7',
  'type': {'@uuid': '3878c04e-251e-4a43-b700-af1cfea30730',
   'id': 143,
   'created': '2025-05-19T16:27:02.748',
   'lastModified': '2025-05-19T16:27:02.749',
   'generalName': 'sound velocity sensor',
   'systemName': 'sound_velocity_sensor',
   'description': 'Instrument that measures the velocity of sound in seawater.',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/L05/current/185',
   'vocableGroup': '85694c85-5aee-441f-a88a-a6bb8f1d0885'},
  'version': 0},
 {'@uuid': 'b06e4ed6-0819-463c-a93e-10625c49951f',
  'id': 2869,
  'lastModified': '2024-01-17T19:17:14.56',
  'code': 'vessel:mya_ii:resonsvp70_0618160',
  'shortName': 'ResonSVP70_0618160',
  'longName': 'Reson SVP 70',
  'description': '',
  'model': 'SVP 70',
  'manufacturer': 'Reson',
  'serialNumber': '0618160',
  'inventoryNumber': '',
  'citation': '10013/sensor.8b471996-bfc4-44a4-86ef-301ebaa68869',
  'parentId': 456,
  'status': 'a080ff68-30b2-450a-9a44-06ecd244c0b7',
  'type': {'@uuid': '1e4b1257-131f-465b-81d7-ede5e893db99',
   'id': 269,
   'created': '2025-05-19T16:28:04.759',
   'lastModified': '2025-05-19T16:28:04.76',
   'generalName': 'acoustic backscatter sensor',
   'systemName': 'acoustic_backscatter_sensor',
   'description': 'Instrument that measures the amount of sound energy transmitted into the water column returned to the instrument.',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/L05/current/183',
   'vocableGroup': '85694c85-5aee-441f-a88a-a6bb8f1d0885'},
  'version': 2},
 {'@uuid': 'a4b61bd8-b36f-4ad9-8fa4-c295f77e4ab2',
  'id': 7464,
  'lastModified': '2024-01-17T19:17:14.618',
  'code': 'vessel:mya_ii:ufz_baro_106884',
  'shortName': 'UFZ_Baro_106884',
  'longName': 'UFZ Barologger 0012106884',
  'description': 'The Barologger Edge uses algorithms based on air pressure only. It measures and logs changes in atmospheric pressure, which are then used to compensate water level readings recorded by a Levelogger Edge, Levelogger Junior Edge, or LTC Levelogger Edge.',
  'model': 'Barologger',
  'manufacturer': 'Solinst',
  'serialNumber': '0012106884',
  'inventoryNumber': '',
  'citation': '10013/sensor.6b510cd0-ce04-4a9b-88cf-33652ca5ec50',
  'parentId': 456,
  'status': 'a080ff68-30b2-450a-9a44-06ecd244c0b7',
  'type': {'@uuid': '9affbf12-c340-42da-b3a9-6969b7fc5fb9',
   'id': 462,
   'created': '2025-05-19T16:29:55.252',
   'lastModified': '2025-05-19T16:29:55.253',
   'generalName': 'data logger',
   'systemName': 'data_logger',
   'description': 'Electronic devices that record data over time or in relation to location either with a built-in instrument or sensor or via external instruments and sensors. ',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/L05/current/DLOG',
   'vocableGroup': '85694c85-5aee-441f-a88a-a6bb8f1d0885'},
  'version': 2},
 {'@uuid': '7400b1f4-17a4-45ef-a581-ab1b7ec7441a',
  'id': 7465,
  'lastModified': '2024-01-17T19:17:14.701',
  'code': 'vessel:mya_ii:ufz_level_78969',
  'shortName': 'UFZ_Level_78969',
  'longName': 'UFZ Levellogger 0171078969',
  'description': 'The LTC Levelogger Edge provides an accurate and convenient method to measure level, temperature and conductivity all in one probe.',
  'model': 'LTC Levelogger Edge ',
  'manufacturer': 'Solinst',
  'serialNumber': '0171078969',
  'inventoryNumber': '',
  'citation': '10013/sensor.fee61211-f93c-47f4-8224-65fa79bf102d',
  'parentId': 456,
  'status': 'a080ff68-30b2-450a-9a44-06ecd244c0b7',
  'type': {'@uuid': '9affbf12-c340-42da-b3a9-6969b7fc5fb9',
   'id': 462,
   'created': '2025-05-19T16:29:55.252',
   'lastModified': '2025-05-19T16:29:55.253',
   'generalName': 'data logger',
   'systemName': 'data_logger',
   'description': 'Electronic devices that record data over time or in relation to location either with a built-in instrument or sensor or via external instruments and sensors. ',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/L05/current/DLOG',
   'vocableGroup': '85694c85-5aee-441f-a88a-a6bb8f1d0885'},
  'version': 2},
 {'@uuid': '43876148-51a7-4b27-967f-62fd716ae3ce',
  'id': 7466,
  'lastModified': '2024-01-17T19:17:14.774',
  'code': 'vessel:mya_ii:ufz_level_78975',
  'shortName': 'UFZ_Level_78975',
  'longName': 'UFZ Levellogger 0171078975',
  'description': 'The LTC Levelogger Edge provides an accurate and convenient method to measure level, temperature and conductivity all in one probe.',
  'model': 'LTC Levellogger Edge',
  'manufacturer': 'Solinst',
  'serialNumber': '0171078975',
  'inventoryNumber': '',
  'citation': '10013/sensor.d89a78f4-7935-4f45-893d-05ae4f6bf28e',
  'parentId': 456,
  'status': 'a080ff68-30b2-450a-9a44-06ecd244c0b7',
  'type': {'@uuid': '9affbf12-c340-42da-b3a9-6969b7fc5fb9',
   'id': 462,
   'created': '2025-05-19T16:29:55.252',
   'lastModified': '2025-05-19T16:29:55.253',
   'generalName': 'data logger',
   'systemName': 'data_logger',
   'description': 'Electronic devices that record data over time or in relation to location either with a built-in instrument or sensor or via external instruments and sensors. ',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/L05/current/DLOG',
   'vocableGroup': '85694c85-5aee-441f-a88a-a6bb8f1d0885'},
  'version': 2},
 {'@uuid': 'd2dbf797-e3e1-429d-b65d-e3f0c1dbd2b0',
  'id': 7467,
  'lastModified': '2024-01-17T19:17:14.851',
  'code': 'vessel:mya_ii:ufz_level_78977',
  'shortName': 'UFZ_Level_78977',
  'longName': 'UFZ Levellogger 071078977',
  'description': 'The LTC Levelogger Edge provides an accurate and convenient method to measure level, temperature and conductivity all in one probe.',
  'model': 'LTC Levellogger Edge',
  'manufacturer': 'Solinst',
  'serialNumber': '071078977',
  'inventoryNumber': '',
  'citation': '10013/sensor.aa414da2-1a87-4337-b364-8e25420bea0e',
  'parentId': 456,
  'status': 'a080ff68-30b2-450a-9a44-06ecd244c0b7',
  'type': {'@uuid': '9affbf12-c340-42da-b3a9-6969b7fc5fb9',
   'id': 462,
   'created': '2025-05-19T16:29:55.252',
   'lastModified': '2025-05-19T16:29:55.253',
   'generalName': 'data logger',
   'systemName': 'data_logger',
   'description': 'Electronic devices that record data over time or in relation to location either with a built-in instrument or sensor or via external instruments and sensors. ',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/L05/current/DLOG',
   'vocableGroup': '85694c85-5aee-441f-a88a-a6bb8f1d0885'},
  'version': 2},
 {'@uuid': '4a7875e1-8159-4861-8bcb-39750b6f8354',
  'id': 7468,
  'lastModified': '2024-01-17T19:17:14.927',
  'code': 'vessel:mya_ii:ufz_level_78743',
  'shortName': 'UFZ_level_78743',
  'longName': 'UFZ Levellogger 0171078743',
  'description': 'Ltc levelogger edge groundwater conductivity datalogger\nThe LTC Levelogger Edge provides an accurate and convenient method to measure level, temperature and conductivity all in one probe.',
  'model': 'Ltc levelogger edge',
  'manufacturer': 'Solinst',
  'serialNumber': '0171078743',
  'inventoryNumber': '',
  'citation': '10013/sensor.4ed83c79-aee6-4852-8d6f-a88b842dadae',
  'parentId': 456,
  'status': 'a080ff68-30b2-450a-9a44-06ecd244c0b7',
  'type': {'@uuid': '9affbf12-c340-42da-b3a9-6969b7fc5fb9',
   'id': 462,
   'created': '2025-05-19T16:29:55.252',
   'lastModified': '2025-05-19T16:29:55.253',
   'generalName': 'data logger',
   'systemName': 'data_logger',
   'description': 'Electronic devices that record data over time or in relation to location either with a built-in instrument or sensor or via external instruments and sensors. ',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/L05/current/DLOG',
   'vocableGroup': '85694c85-5aee-441f-a88a-a6bb8f1d0885'},
  'version': 2},
 {'@uuid': '3fa8f5dc-bc40-4dfe-8de4-8eb5c820ed59',
  'id': 8767,
  'created': '2024-05-07T06:30:05.339',
  'lastModified': '2025-08-29T11:05:15.023',
  'code': 'vessel:mya_ii:moses_moblab',
  'shortName': 'moses_moblab',
  'longName': 'MOSES mobile 10feet laboratory container ',
  'description': '',
  'model': '',
  'manufacturer': '4H-JENA engineering GmbH',
  'serialNumber': '',
  'inventoryNumber': '',
  'citation': '10013/sensor.b566c1fe-6dc5-4283-adf5-4287a541d04f',
  'parentId': 456,
  'status': 'a080ff68-30b2-450a-9a44-06ecd244c0b7',
  'type': {'@uuid': '6a50b863-1a42-40c2-958c-6f94812cc589',
   'id': 246,
   'lastModified': '2022-09-14T07:06:17.886',
   'generalName': 'laboratory',
   'systemName': 'laboratory',
   'description': '',
   'vocabulary': 'AWI',
   'vocableValue': 'AWI',
   'vocableGroup': '85694c85-5aee-441f-a88a-a6bb8f1d0885'},
  'version': 41},
 {'@uuid': '0c31f298-7096-4a98-b707-721b9d1dd2c0',
  'id': 11500,
  'created': '2024-03-19T13:26:36.539',
  'lastModified': '2024-03-19T13:26:36.579',
  'code': 'vessel:mya_ii:weather',
  'shortName': 'Weather',
  'longName': 'Weather Station',
  'description': 'Autonomouos weather station providing air and water temperature, rel. air humidity and air pressure',
  'model': 'PB150',
  'manufacturer': 'Airmar Technology Corporation',
  'serialNumber': '',
  'inventoryNumber': '',
  'citation': '10013/sensor.aea83de7-1506-40cd-ae2c-6a5ee7a7bc86',
  'parentId': 456,
  'status': 'a080ff68-30b2-450a-9a44-06ecd244c0b7',
  'type': {'@uuid': '7be0c605-0621-4425-bfb7-7374c5fccded',
   'id': 172,
   'created': '2025-05-19T16:27:17.253',
   'lastModified': '2025-05-19T16:27:17.253',
   'generalName': 'meteorological package',
   'systemName': 'meteorological_package',
   'description': 'Instrument that makes routine meteorological measurements on the atmosphere, typically air pressure, temperature and humidity.',
   'vocabulary': 'NERC',
   'vocableValue': 'https://vocab.nerc.ac.uk/collection/L05/current/102',
   'vocableGroup': '85694c85-5aee-441f-a88a-a6bb8f1d0885'},
  'version': 1}]